;uProcessor Final Project
;File name: pj5.inc
;Date: 2020/1/4
;By B10707009 and B10707049
;National Taiwan University of Science And Technology
;Department of Electrical Engineering

print_up_right      PROTO
print_up_left       PROTO
print_down_right    PROTO
print_down_left     PROTO 
print_up            PROTO
print_down          PROTO
print_left          PROTO
print_right         PROTO
pj5_Init            PROTO
TankProcess         PROTO 
musicInit           PROTO
Playmusic           PROTO  
PlayLoopMusic       PROTO
